version: '3.4'
services:
  bot-discord:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot-discord
    user: 1004:1004
    volumes:
      - ./cfg:/dggiscord/cfg
    restart: unless-stopped
    network_mode: host
